### ISSUE TITLE
Extract `OSMAXX` independent utilities to a separate repository and publish it on pypi

### ISSUE THREAD

**Issue by ghost** [geometalab/osmaxx#205]
Extract the [utility functions](https://github.com/geometalab/osmaxx/blob/feature/203_add_utility_shortcut_functions/osmaxx-py/osmaxx/utilities/shortcuts.py) `get_object_or_none` and `get_list_or_none` from #203 into its own repository and publish it on pypi for independent usage.

**Comment by das-g** [comment]
Have we checked whether something like this already exists?

**Comment by njordan-hsr** [comment]
There are some snippets that exist, and AFAIK there are projects that provide this as well, but they usually provide much much more. Since they are very simple functions, I don't think it warrants another dependency.

**Comment by hixi** [comment]
There is not much left other than these two function, which don't warrant the overhead of PyPI releases.

**Comment by das-g** [comment]
Actually, some little base classes like [`ChoicesEnum`](https://github.com/geometalab/osmaxx-postgis-conversion/blob/88bba480a68ea9023200204ea133f4f1f5105a79/conversion_service/shared/__init__.py#L6) might be worth sharing, so they can be used by the UI project (`github.com/geometalab/osmaxx`) and the conversion service (`github.com/geometalab/osmaxx-postgis-conversion`).

**Comment by hixi** [comment]
Actually, we discussed this when we wrote that code on the postgis-conversion side, and agreed, that this is just something that belongs to the interface (and can be queried using the `OPTIONS` http-verb). And I'm absolutely against polluting PyPI with a project specific helper class (or method), just because we aren't willing to join the projects.
