### ISSUE TITLE
Better directory structure in garmin result ZIP archive files

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#354]
Currently, the top level folder in the garmin download ZIP archive is called `tmp`. When unpacking several downloaded archives in the same location, this leads to name collisions. Also, that folder name isn't "speaking" enough. The names of the subfolder ain't any better, either.

Analogous directory names and directory structure as for the GIS formats should be used for the garmin format, too.

**Comment by das-g** [comment]
Hint: If the [`zip` cli command](http://linuxcommand.org/man_pages/zip1.html) is too clumsy, look into [Python's `zipfile`](https://docs.python.org/3/library/zipfile.html).

**Comment by hixi** [comment]
I disagree that the same structure should be used, especially since the data aggregation doesn't apply (statistics etc.). I do think a better structure should be used, and I'm for a [sub-folder named garmin](https://github.com/geometalab/osmaxx-conversion-service/commit/f9b86d07758f650f59522c91af87cfaca320c1e5).
