### ISSUE TITLE
Fix country filter for MS IE

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx#364]
# to reproduce
1. click "Existing excerpt / country"
2. enter `ita` into the "Filter excerpts ..." field

## expected
* Excerpt list is filtered accordingly: only "Italy" and "Mauritania" are still visible

## observed
* All entries of the excerpt list remain visible

**Comment by hixi** [comment]
Problem identified: the hide()/show() adds/removes the css property `display` with the appropriate attributes. These are not supported by IE (and supposedly also not for Safari), which therefore doesn't work. The only solution is to remove all hidden elements, and add them back - which seems a lot of work. I would consider using [underscore.js](http://underscorejs.org/#filter) for this.

**Comment by das-g** [comment]
An alternative to [underscore.js's `_.filter()`](http://underscorejs.org/#filter) would be [`Array.prototype.filter()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter), available in IE 9 and better.

**Comment by hixi** [comment]
Found a possible solution: http://www.lessanvaezi.com/filter-select-list-options/ or something like
http://www.barelyfitz.com/projects/filterlist/

**Comment by wasabideveloper** [comment]
Idea to fix the problem:
Do the following only if the browser is an IE:
- Store select.html() in a variable
- On filtering by user remove the options from the selectbox
- On remove of filter reaply select.html(...)
- On filter change reaply select.html(...) and filter again

**Only do this for IE because of the bad performance and because a existing selection will be throwed away on filtering!**

**Comment by hixi** [comment]
I think this is the best solution _EVER_ http://ajax911.com/hide-options-selecbox-jquery/ _<span>_ to the rescue :eyes:
