### ISSUE TITLE
Invalid geometry on worker doesn't lead to exception

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx#541]
`Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -3.9969260000000002 47.72466 at -3.9969260000000002 47.72466`
should actually be an exception and show up in the sentry logs.

**Comment by hixi** [comment]
Even though this currently doesn't happen anymore (we currently send valid geometries) and is unlikely to happen again, errors should still lead to an exception.

**Comment by hixi** [comment]
investigate, if setting a variable in the sql-scripts (`set -u` bash equivalent for sql) would help, or if sqlalchemy can be invoked more strictly.

**Comment by das-g** [comment]
### Analysis

#### Cause of the error

A similar message can be provoked with
```python
from sqlalchemy import create_engine, func
from sqlalchemy.sql import select
from sqlalchemy.engine.url import URL

from tests.inside_worker_test.conftest import slow


@slow
def test_selfintersection():
    _local_db_connection_parameters = dict(
        username='postgres',
        password='postgres',
        port=54321,
        database='postgres',
        host='127.0.0.1',
    )
    local_db_connection = URL('postgresql', **_local_db_connection_parameters)
    local_db_engine = create_engine(local_db_connection)
    local_db_engine.execute(
        select(
            [
                func.ST_Intersection(
                    func.ST_GeomFromText(
                        'POLYGON((0 0,4 0,4 4,0 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))'
                    ),  # valid
                    func.ST_GeomFromText(
                        'POLYGON((0 0,4 0,0 4,4 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))'
                    ),  # self-intersecting
                )
            ]
        )
    )
```
&rArr;
```
self = <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x7fa785198b38>, cursor = <cursor object at 0x7fa7852166d8; closed: -1>
statement = 'SELECT ST_AsBinary(ST_Intersection(ST_GeomFromText(%(ST_GeomFromText_1)s), ST_GeomFromText(%(ST_GeomFromText_2)s))) AS "ST_Intersection_1"'
parameters = {'ST_GeomFromText_1': 'POLYGON((0 0,4 0,4 4,0 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))', 'ST_GeomFromText_2': 'POLYGON((0 0,4 0,0 4,4 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))'}
context = <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x7fa78517b2b0>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.InternalError: (psycopg2.InternalError) Error performing intersection: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 2 2 at 2 2
E        [SQL: 'SELECT ST_AsBinary(ST_Intersection(ST_GeomFromText(%(ST_GeomFromText_1)s), ST_GeomFromText(%(ST_GeomFromText_2)s))) AS "ST_Intersection_1"'] [parameters: {'ST_GeomFromText_2': 'POLYGON((0 0,4 0,0 4,4 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))', 'ST_GeomFromText_1': 'POLYGON((0 0,4 0,4 4,0 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))'}]

/home/das-g/.virtualenvs/osmaxx/lib/python3.4/site-packages/sqlalchemy/engine/default.py:450: InternalError
```

The only place where we use `ST_Intersection` is [in the SQL `VIEW`s](https://github.com/geometalab/osmaxx-frontend/blob/2.0.0/osmaxx/conversion/converters/converter_gis/helper/osm_importer.py#L111) we use to export the additional layers from openstreetmapdata.com coastlines, land poygons and sea polygons:
```python
from sqlalchemy import MetaData, Table, create_engine, func
# ...
func.ST_Multi(func.ST_Intersection(source_table_meta.c.wkb_geometry, extent.ewkt)),
# ...
```

(`ST_Intersects` would also cause an error when one of the arguments is self-intersecting, but the error message would be different than with `ST_Intersection`:
```
self = <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x7f69575c3358>, cursor = <cursor object at 0x7f69575ff6d8; closed: -1>
statement = 'SELECT ST_Intersects(ST_GeomFromText(%(ST_GeomFromText_1)s), ST_GeomFromText(%(ST_GeomFromText_2)s)) AS "ST_Intersects_1"'
parameters = {'ST_GeomFromText_1': 'POLYGON((0 0,4 0,4 4,0 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))', 'ST_GeomFromText_2': 'POLYGON((0 0,4 0,0 4,4 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))'}
context = <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x7f69575b50f0>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.InternalError: (psycopg2.InternalError) GEOSIntersects: TopologyException: side location conflict at 1 1
E       CONTEXT:  SQL function "st_intersects" statement 1
E        [SQL: 'SELECT ST_Intersects(ST_GeomFromText(%(ST_GeomFromText_1)s), ST_GeomFromText(%(ST_GeomFromText_2)s)) AS "ST_Intersects_1"'] [parameters: {'ST_GeomFromText_1': 'POLYGON((0 0,4 0,4 4,0 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))', 'ST_GeomFromText_2': 'POLYGON((0 0,4 0,0 4,4 4,0 0),(1 1, 2 1, 2 2, 1 2,1 1))'}]

/home/das-g/.virtualenvs/osmaxx/lib/python3.4/site-packages/sqlalchemy/engine/default.py:450: InternalError
```

We know that it was the second, not the first argument that was self-intersecting, as the `ST_Intersection` error message would otherwise have mentioned `geom 0` rather than `geom 1`.)

**So `extent.ewkt` was self-intersecting.** Changes already made to the frontend should avoid that in the future.

#### Why the error didn't lead to an exception

Other than syntactical errors, runtime SQL errors in `VIEW`s occur when querying the `VIEW`, not when creating it. If we'd query the affected `VIEW`(s) with SQLAlchemy/GeoAlchemy 2 in our python code, we'd indeed have gotten an exception there.

The views created for these layers however are only ever read by `ogr2ogr` ([here](https://github.com/geometalab/osmaxx-frontend/blob/2.0.0/osmaxx/conversion/converters/converter_gis/extract/db_to_format/extract.py#L54), implicitly (whole `SCHEMA` `view_osmaxx`)). If `ogr2ogr` would exit with a non-zero status, we'd get an Exception here, too (because we use `check_output`), but while `ogr2ogr` does output the error message, it doesn't signal failure for this kind of SQL error. (According to @sfkeller, [GeoConverter](https://geoconverter.hsr.ch/) has the same issue.)

The `ogr2ogr` command [doesn't seem to](http://www.gdal.org/ogr2ogr.html) have any options to influence this. If I understand [the documentation for GDAL's PostgreSQL/PostGIS driver](http://www.gdal.org/drv_pg.html) correctly, the API would allow to collect errors by wrapping the causing code in a `CPLPushErrorHandler()`/`CPLPopErrorHandler()` pair, but it looks like the `ogr2ogr` CLI doesn't use/expose this possibility.

**Comment by hixi** [comment]
Is it OK to close this issue, since we can't do anything on our side?

Reasoning:
Error is being swallowed silently without throwing an error, if it can be fixed at all, it can only be fixed upstream in OGR/GDAL - unless we parse the generated output, which is a bad idea.
