### ISSUE TITLE
links in email are http instead of https

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx#723]
change the links in the email to https in production.

**Comment by das-g** [comment]
I've just tested this in production. Doesn't work there, even though 64903bb53a3630c2ecd3db1cfda82aac2ecbb1cf is included in tag&nbsp;`v3.0.0 `and https://osmaxx.hsr.ch/version/ reports the version online to be `v3.0.0 `.

Here's the mail I got:

> The extraction order #275 "St. Wendelin" has been processed.
> Results available for download:
> - Garmin navigation &amp; map data (http://osmaxx.hsr.ch/media/osmaxx/outputfiles/51780327-984c-4771-a042-66e95d25e94d/st-wendelin_wgs-84_2016-11-08_garmin_full-detail.zip)
> 
> 
> View the complete order at http://osmaxx.hsr.ch/exports/

Note the `http://` instead of the `https://` in both links.

Reopening.

**Comment by das-g** [comment]
For the fix from #730 to work, environment variable `DJANGO_OSMAXX_SECURED_PROXY` needs to be set to `TRUE` for all setups where HTTP**S** is handled by a proxy (nginx in our case).

I can't currently tell whether our deployment scripts do that, because https://github.com/geometalab/osmaxx-deploy is not up to date.

**Comment by hixi** [comment]
has been fixed with redeploying with correct settings.
