### ISSUE TITLE
Failed exports

### ISSUE THREAD

**Issue by geoBWM** [geometalab/osmaxx#774]
The extraction order `#339` "Port-au-Prince" (as GeoPackage & SpatialLite) failed twice - once as "full detail", once "simplified".

**Comment by das-g** [comment]
This might have been due to the same cause as #829. (Hard to tell because our error logging back then wasn't as good as the one we have now.)

#829 has been fixed recently with #830.

Closing this issue as a duplicate (although it has been first). If this turns out to still be an issue, please comment and/or re-open.
